name: buncher
description: buncher Example
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  provider: ^4.0.2
  firebase_auth:
  google_sign_in: ^4.0.1+3
  shared_preferences: ^0.5.1+1
  # native_widgets: ^1.0.1
  scoped_model: ^1.0.1
  json_annotation: ^2.0.0
  # local_auth: ^0.5.2+3
  get_it: ^1.0.3+2
  intl: 0.15.7
  uuid: ^2.0.4
  # cloud_firestore: ^0.8.2
  google_maps_flutter: ^0.5.21+15


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/carsplash.png
  - assets/noimage.jpg

image_picker: ^0.4.10

